= Axon Cookbook

Axon is a lightweight framework that helps developers build scalable and extensible applications by addressing these concerns directly in the architecture. This cookbook will provide you with recipes to implement the Axon Framework. The recipes vary from basic recipes of Axon based applications (setup, testing, upcasting, etc.) to specific advanced use cases (distributed command bus, parameter resolvers, etc.).

The recipes are sorted on milestones versions of the Axon Framework. If a recipe is not yet available for your version, please check another version first, most of the implementation should overlap. If that recipe covers not enough, or too much has changed on the topic, please https://axoniq.io/[contact us]. 

The recipes are a guideline on how you can use the Axon Framework. The https://docs.axonframework.org/[reference guide] explains the concepts of the framework.

If you're interested in helping out building the Axon Framework, check the https://github.com/AxonFramework/AxonFramework[Github] page. Help is always welcome.

If you're interested in helping out writing recipes, check the https://github.com/AxonIQ/axoniq-cookbook[Github] page. Help is always welcome.

For more questions about the Axon Framework or the products of AxonIQ, check the https://axoniq.io/[website] of AxonIQ.

