== Recipe - Axon Framework in a Spring Boot application

This recipe gives the basic steps for creating an Axon Framework based application with the use of Spring Boot. For the recipe creating an Axon Framework based application without the use of Spring Boot, go http://www.axoniq.io[here]

This recipe will focus on the implementation of the application and not the concepts were the Axon Framework is based on. For the concepts of the Axon Framework go to the http://www.axoniq.io[Axon Framework reference guide]

All recipes are based on one domain, the bank. Axon Framework is in good use for a domain like a bank. A person wants to open a bank account to deposit and withdraw money from. Over time, the customer wants to see the current state of the bankaccount and see which transactions have taken place to get to the current amount. The events that have been applied over time are the basis of the transaction log and the current amount is representation of the state.

Of course, over time the bank will find out that there can be more than one type of bank account that can be created or not all values required for withdraw are in the event. In that case, we will need to change the events and maybe adjust the events. We start simple in this example application, just a basic set of events. But at the bottom you can find a reference to other recipes for cooking upcasters, event stores, command busses and more. Let's first start with this recipe.

=== General
- Cooks in: 30 minutes
- Difficulty: easy

=== Ingredients
* *Dependencies*

[width="100%",frame="topbot",options="header"]
|======================
|*Dependency*                           |*Version*
|Axon Framework                         |3.0.6
|Spring Boot starter for Axon Framework |3.0.6
|Spring Boot                            |1.5.8.RELEASE
|Kotlin                                 |1.1.51
|======================

* *Axon Framework components*

[width="100%",frame="topbot"]
|======================
|Aggregate
|Command handlers
|Event handlers
|Event Sourcing handlers
|======================

=== Method

* *Set up the Spring Boot application*

For the creation of a simple Spring Boot application go to http://start.spring.io[start.spring.io].
Configure the application metadata as preferred. Add `Web`, `JPA` and `HSQLDB` as dependencies. After configuring everything download the Spring Boot application and load as a project in the preferred IDE.

* *Add dependencies*

Navigate to the pom.xml. There will be already a set of Spring Boot related dependencies. Add the Axon Framework Spring Boot starter dependency to the list.
[source, xml]
----
<dependency>
    <groupId>org.axonframework</groupId>
    <artifactId>axon-spring-boot-starter</artifactId>
    <version>3.0.6</version>
</dependency>
----

For the value objects we will make use of https://kotlinlang.org/[Kotlin]. To use Kotlin, add the following dependency also to the list of dependencies.
[source, xml]
----
<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-stdlib</artifactId>
    <version>1.1.51</version>
</dependency>
----

* *Start the application*

Run the application, if everything is done as explained. The Spring Boot application should run with no problem. If not, check configuration and Spring documentation before going to the next step.

* *Create an endpoint*

To do something with our application we will need an endpoint. 


X. Add service
X. Add command
X. Add aggregate
X. Add event
X. Add event handler
X. Add view
X. Add endpoint to retrieve data



====== For any question about the recipe, please contact
- http://www.axoniq.io[Axon user group]
- http://www.axoniq.io[AxonIQ support]

====== Other readings and recipes
- How to write an Aggregate test
- How to write an Upcaster
- How to add a Saga
- How to add an Entity under an Aggregate
- Axon Framework reference guide
