== Recipe - Axon Framework in a Spring Boot application

This recipe gives the basic steps for creating an Axon Framework based application with the use of Spring Boot. For the recipe creating an Axon Framework based application without the use of Spring Boot, go http://www.axoniq.io[here]

This recipe will focus on the implementation of the application and not the concepts were the Axon Framework is based on. For the concepts of the Axon Framework go to the http://www.axoniq.io[Axon Framework reference guide]

All recipes are based on one domain, the bank. Axon Framework is in good use for a domain like a bank. A person wants to open a bank account to deposit and withdraw money from. Over time, the customer wants to see the current state of the bankaccount and see which transactions have taken place to get to the current amount. The events that have been applied over time are the basis of the transaction log and the current amount is representation of the state.

Of course, over time the bank will find out that there can be more than one type of bank account that can be created or not all values required for withdraw are in the event. In that case, we will need to change the events and maybe adjust the events. We start simple in this example application, just a basic set of events. But at the bottom you can find a reference to other recipes for cooking upcasters, event stores, command busses and more. Let's first start with this recipe.

=== General
- Cooks in: 30 minutes
- Difficulty: easy

=== Ingredients
* *Dependencies*
- Spring Boot
- Axon Framework v3.0.6
- Spring Boot starter for Axon Framework
- Kotlin

* *Axon Framework components*
- Aggregate
- CommandHandlers
- Eventsourcing handlers
- EventHandlers

=== Method

1. Set up the application at Spring 
- start.spring.io
- Fill in properties of the application (name, package, etc.)
- Download the project from start.spring.io and open in your IDE

2. Add dependencies for Axon Framework
```
<dependency>
    <groupId>org.axonframework</groupId>
    <artifactId>axon-spring-boot-starter</artifactId>
    <version>3.0.6</version>
</dependency>
```

X. Run the application, if everything is done as explained. The Spring Boot application should just run
```
2017-10-26 18:01:22.755  INFO 5602 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase -2147482648
2017-10-26 18:01:22.759  INFO 5602 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase -1073741824
2017-10-26 18:01:22.761  INFO 5602 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2017-10-26 18:01:22.786  INFO 5602 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2017-10-26 18:01:22.790  INFO 5602 --- [           main] io.axoniq.axonbank.AxonBankApplication   : Started AxonBankApplication in 4.319 seconds (JVM running for 5.367)
```
X. Add endpoint
To do something with our application we will need an endpoint. 


X. Add service
X. Add command
X. Add aggregate
X. Add event
X. Add event handler
X. Add view
X. Add endpoint to retrieve data



====== For any question about the recipe, please contact
- http://www.axoniq.io[Axon user group]
- http://www.axoniq.io[AxonIQ support]

====== Other readings and recipes
- How to write an Aggregate test
- How to write an Upcaster
- How to add a Saga
- How to add an Entity under an Aggregate
- Axon Framework reference guide
