= Recipe

- Cooks in - 30 minutes
- Difficulty - easy

===  Testing the Axon Application

This recipe will give an overview of how to test your Axon Application. This recipe is based on the application that is created in the link:16_basic-axon-framework-application-with-spring-boot.adoc[Simple application using Axon Framework and Spring Boot] recipe. Axon Framework provides a Fixture test setup to see whether a Command is handled and the Event(s) expected applied.

Next to the test of an Aggregate, this recipe will give examples of testing the `AccountController` and the `AccountProjector`.

===== Ingredients

[width="100%",frame="topbot",options="header"]
|======================
|*Dependency*                           |*Version*
|Axon Framework                         |3.1.X
|Spring Boot starter for Axon Framework |3.1.X
|Axon Test                              |3.1.X
|Spring Boot                            |1.5.X.RELEASE
|Kotlin                                 |1.1.X
|Mockito Kotlin                         |1.5.X
|======================

[width="100%",frame="topbot"]
|======================
|*Axon Framework components*
|Fixture Configuration
|Aggregate
|Command handlers
|Event handlers
|Event Sourcing handlers
|======================

===== Method

*1 Add dependencies*

For testing the Axon Application we need two extra dependencies.

The first one is the Kotlin version of http://site.mockito.org/[Mockito]:

[source, xml]
----
<dependency>
    <groupId>com.nhaarman</groupId>
    <artifactId>mockito-kotlin</artifactId>
    <version>1.5.X</version>
</dependency>
----

The second one is the test module of the Axon Framework. The module provides configuration for testing of Aggregates and Sagas.
[source, xml]
----
<dependency>
    <groupId>org.axonframework</groupId>
    <artifactId>axon-test</artifactId>
    <version>3.1</version>
</dependency>
----

*2 Add AccountController test*

*3 Add Account Aggregate test*

*4 Add AccountProjector test*



====== Other readings and recipes


====== For any question about the recipe or Axon Framework in general, please contact us via
- https://groups.google.com/forum/#!forum/axonframework[Axon user group]
- http://www.axoniq.io[AxonIQ support]